name: Check for new reports

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-python@main
        with:
          python-version: '3.12'
      - run: pip install -r requirements.txt
      - environment: env for scripts
      - name: Run check script
        run: python download.py
        env:
          SLACK_HOOK_LOCAL_CITY: ${{ secrets.SLACK_HOOK_LOCAL_CITY }}