name: Check for new reports

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@main
      with:
        python-version: '3.12'
    - run: pip install -r requirements.txt
    - name: Run check script
      env:
        SLACK_HOOK_LOCAL_CITY: ${{ secrets.SLACK_HOOK_LOCAL_CITY }}
      run: python download.py