name: Check for new reports

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

jobs:
  fetch:
    runs-on: ubuntu-latest
    environment: env for scripts
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-python@main
        with:
          python-version: '3.12'
      - run: pip install -r requirements.txt
      - name: Run check script
        run: python download.py
        env:
          SLACK_HOOK_LOCAL_CITY: ${{ secrets.SLACK_HOOK_LOCAL_CITY }}
      - name: Add and commit
        id: add_commit
        uses: EndBug/add-and-commit@main
        with:
          committer_name: Automated
          committer_email: actions@users.noreply.github.com
          message: "add latest data"